In [26]:
import pandas as pd
import numpy as np

In [7]:
pd.__version__

'3.0.6'

In [8]:
df = pd.read_csv("car_fuel_efficiency_2026.csv")

In [11]:
df.shape

(10000, 11)

In [13]:
df["fuel_type"].unique()

<StringArray>
['Gasoline', 'Diesel', 'Hybrid']
Length: 3, dtype: str

In [15]:
df.isnull().sum()

model_year               0
origin                   0
fuel_type                0
drivetrain               0
num_doors                0
engine_displacement      0
num_cylinders            0
horsepower             877
vehicle_weight           0
acceleration           264
fuel_efficiency_mpg      0
dtype: int64

In [17]:
df["origin"].unique()

<StringArray>
['Europe', 'Asia', 'USA']
Length: 3, dtype: str

In [18]:
asia_cars = df[df["origin"] == "Asia"]

In [19]:
asia_cars.head()

,model_year,origin,fuel_type,drivetrain,num_doors,engine_displacement,num_cylinders,horsepower,vehicle_weight,acceleration,fuel_efficiency_mpg
2,1996,Asia,Gasoline,Front-wheel drive,5,2320,6,267.0,4240,17.3,27.5
6,1992,Asia,Gasoline,Front-wheel drive,2,2270,6,250.0,4310,21.7,26.8
8,1997,Asia,Gasoline,Rear-wheel drive,3,2330,6,251.0,4230,19.5,30.9
10,1978,Asia,Gasoline,All-wheel drive,3,2410,6,NaN,4420,19.5,26.8
15,2007,Asia,Diesel,Front-wheel drive,4,2170,5,226.0,3950,18.0,35.4


In [20]:
asia_cars["fuel_efficiency_mpg"].max()

np.float64(41.2)

In [21]:
df["fuel_efficiency_mpg"].max()

np.float64(41.2)

In [22]:
df["horsepower"].median()

np.float64(254.0)

In [23]:
df["horsepower"].mode()

0    252.0
Name: horsepower, dtype: float64

In [24]:
horsepower_filled = df["horsepower"].fillna(252.0)

In [25]:
horsepower_filled.median()

np.float64(252.0)

In [34]:
X = asia_cars[["vehicle_weight", "model_year"]].head(7).to_numpy()

In [35]:
y = np.array([1100, 1300, 800, 900, 1000, 1100, 1200])

In [30]:
X

array([[4240, 1996],
       [4310, 1992],
       [4230, 1997],
       [4420, 1978],
       [3950, 2007],
       [4750, 2021],
       [4450, 2019]])

In [31]:
XTX = X.T @ X
XTX

array([[131950500,  60750580],
       [ 60750580,  28041424]])

In [32]:
w = np.linalg.inv(X.T @ X) @ X.T @ y
w

array([-0.00714792,  0.03046659])

In [33]:
w.sum()

np.float64(0.023318664772994352)